services:
  mysql_fiber_gorm_rakamin:
    image: mysql:8.0.30
    container_name: mysql_fiber_gorm_rakamin
    ports:
      - 3306:3306
    volumes:
      - mysql_fiber_gorm_rakamin:/var/lib/mysql
    env_file:
      - .env
    environment:
       MYSQL_ROOT_PASSWORD : ${mysql_password}
       MYSQL_PASSWORD : ${mysql_password}
       MYSQL_USER : ${mysql_username}
       MYSQL_DATABASE : ${mysql_dbname}

volumes:
  mysql_fiber_gorm_rakamin: {}